package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import application.Model;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class AddUpdatePlaneController {
	@FXML
	private TextField id;
	@FXML
	private TextField name;
	@FXML
	private TextField type;
	@FXML
	private TextField seats;
	@FXML
	private Button update;
	@FXML
	private Label alert;
	private String Id;
	private Model model = new Model();
	private Connection myConn = model.connect("sa", "bob1234");
	public void setScene(String operation) throws SQLException {
		if(operation.equals("Update")) {
			id.setDisable(true);
			ResultSet q = model.getData(myConn, "*", "AIRPLANE", "AIRPLANE_ID ='"+Id+"'");
			if(q.next()) {
					
				id.setText(q.getString("AIRPLANE_ID").trim());
				name.setText(q.getString("AIRPLANE_NAME").trim());
				type.setText(q.getString("TYPE").trim());
				seats.setText(q.getString("NUMBER_OF_SEATS").trim());
			}
			
		}else {
			update.setText("ADD");
		}
		
	}
	// Event Listener on Button[#update].onAction
	@FXML
	public void update(ActionEvent event) {
		// TODO Autogenerated
		if(name.getText().trim().isEmpty() || id.getText().trim().isEmpty() || type.getText().trim().isEmpty() || seats.getText().trim().isEmpty() ) {
			alert.setText("Fill empty fields");
			return;
		}
		
		if(update.getText().equals("Update")) {
			model.update(myConn,"AIRPLANE","AIRPLANE_NAME='"+name.getText().trim()+"',TYPE = '"+type.getText().trim()+"',NUMBER_OF_SEATS ="+Integer.parseInt(seats.getText().trim()),"AIRPLANE_ID ='"+id.getText().trim()+"'");
			alert.setText("Updated successfully");
		}else if(update.getText().equals("ADD")) {
			
			try {
				model.Insert(myConn,"AIRPLANE","'"+id.getText().trim()+"','"+name.getText().trim()+"','"+type.getText().trim()+"',"+Integer.parseInt(seats.getText().trim()));
			} catch (NumberFormatException | SQLException e) {
				// TODO Auto-generated catch block
				alert.setText("An error occured while adding");
				e.printStackTrace();
			} 
			alert.setText("Added successfully");
		}
		
	}
	public void setId(String id) {
		this.Id = id;
	}
}
