package Controller;

import java.io.IOException;
import java.sql.SQLException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;

public class MainController {
	@FXML
	private FlowPane employeeView;
	@FXML
	private FlowPane flightView;
	@FXML
	private FlowPane planeView;

	// Event Listener on FlowPane[#employeeView].onMouseEntered
	@FXML
	public void employeeMouseEntered(MouseEvent event) {
		// TODO Autogenerated
		employeeView.setOpacity(1);
	}
	// Event Listener on FlowPane[#employeeView].onMousePressed
	@FXML
	public void employeePressed(MouseEvent event) throws IOException, SQLException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/References/EmployeePage.fxml"));
		EmployeeController controller = new EmployeeController();
		loader.setController(controller);
		Parent root = null;
		root = loader.load();
		controller.setScene();
		Stage stage = (Stage)employeeView.getScene().getWindow();
		stage.close();
		stage = new Stage();
		Scene scene = new Scene(root);
		stage.setScene(scene);
		stage.setTitle("Employees");
		stage.show();
		stage.setResizable(false);//to disable the maximize button 
		//to remove all the window button
		//stage.initStyle(StageStyle.UNDECORATED);
	}
	// Event Listener on FlowPane[#employeeView].onMouseExited
	@FXML
	public void employeeMouseExited(MouseEvent event) {
		// TODO Autogenerated
		employeeView.setOpacity(0.9);
	}
	// Event Listener on FlowPane[#flightView].onMouseEntered
	@FXML
	public void flightMouseEntered(MouseEvent event) {
		// TODO Autogenerated
		flightView.setOpacity(1);
	}
	// Event Listener on FlowPane[#flightView].onMousePressed
	@FXML
	public void flightPressed(MouseEvent event) throws IOException, SQLException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/References/FlightPage.fxml"));
		FlightController controller = new FlightController();
		loader.setController(controller);
		Parent root = null;
		root = loader.load();
		controller.setScene();
		Stage stage = (Stage)employeeView.getScene().getWindow();
		stage.close();
		stage = new Stage();
		Scene scene = new Scene(root);
		stage.setScene(scene);
		stage.setTitle("Flights");
		stage.show();
		stage.setResizable(false);//to disable the maximize button 
	}
	// Event Listener on FlowPane[#flightView].onMouseExited
	@FXML
	public void flightMouseExited(MouseEvent event) {
		// TODO Autogenerated
		flightView.setOpacity(0.9);
	}
	// Event Listener on FlowPane[#planeView].onMouseEntered
	@FXML
	public void planeMouseEntered(MouseEvent event) {
		// TODO Autogenerated
		planeView.setOpacity(1);
	}
	// Event Listener on FlowPane[#planeView].onMousePressed
	@FXML
	public void planePressed(MouseEvent event) throws IOException, SQLException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/References/PlanePage.fxml"));
		PlaneController controller = new PlaneController();
		loader.setController(controller);
		Parent root = null;
		root = loader.load();
		controller.setScene();
		Stage stage = (Stage)employeeView.getScene().getWindow();
		stage.close();//close current window
		stage = new Stage();
		Scene scene = new Scene(root);
		stage.setScene(scene);
		stage.setTitle("Planes");
		stage.show();
		stage.setResizable(false);//to disable the maximize button 
	}
	// Event Listener on FlowPane[#planeView].onMouseExited
	@FXML
	public void planeMouseExited(MouseEvent event) {
		// TODO Autogenerated
		planeView.setOpacity(0.9);
	}
}
