USE AirlineSystemDB
go

--PROCEDURE RETURN TO US ALL THE EMPLOYEES ASSOCIATED WITH A CERTIAN FLIGHT

CREATE Procedure FLIGHT_EMPLOYEES @FLIGHT_NUM CHAR(15) AS
BEGIN
select F.FLIGHT_NUMBER, E.EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, ADDRESS, EMAIL, PHONE_NUMBER
FROM FLIGHT AS F,EMPLOYEE AS E
WHERE F.FLIGHT_NUMBER=@FLIGHT_NUM AND E.EMPLOYEE_ID=F.PILOT
UNION
select A.FLIGHT_NUMBER, E.EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, ADDRESS, EMAIL, PHONE_NUMBER 
FROM ASSISTANT AS A,EMPLOYEE AS E
WHERE A.FLIGHT_NUMBER=@FLIGHT_NUM AND E.EMPLOYEE_ID=A.EMPLOYEE_ID
ORDER BY E.EMPLOYEE_ID
END

EXEC FLIGHT_EMPLOYEES 'AI333'
Drop procedure FLIGHTEMPLOYEES
