CREATE PROCEDURE FLIGHT_PASSENGERS @flightNum CHAR(15) AS
BEGIN
	SELECT P.PASS_ID,P.NAME,P.BIRTHDAY,P.ADDRESS,P.PHONE_NUMBER
	FROM PASSENGER P,RESERVATION R
	WHERE R.FID = @flightNum AND P.PASS_ID=R.PID
	ORDER BY P.PASS_ID
END

EXEC FLIGHT_PASSENGERS 'AI381'

DROP PROCEDURE FLIGHT_PASSENGERS

