use AirlineSystemDB
go

CREATE PROCEDURE RESERVE @FID CHAR(15),@CLASS VARCHAR(15),@PID CHAR(10),@PRICE FLOAT OUT,@SEAT INTEGER OUT
AS
DECLARE @duration FLOAT,@SEATN INTEGER;
BEGIN
	SET @SEATN = (SELECT ISNULL(MAX(R.SEAT_NUMBER),0) FROM FLIGHT F,RESERVATION R WHERE F.FLIGHT_NUMBER=@FID AND R.FID=F.FLIGHT_NUMBER AND R.CLASS = @CLASS)+1;	if(@CLASS = 'FIRST' AND @SEATN=1)	BEGIN		SET @SEAT = @SEATN;	END	if(@CLASS = 'BUSINESS' AND @SEATN=1)	BEGIN		SET @SEAT = 10 + @SEATN;	END	if(@CLASS = 'ECONOMY' AND @SEATN=1)	BEGIN		SET @SEAT = 40 + @SEATN;	END	if(@SEATN > 1)	BEGIN		SET @SEAT = @SEATN	END

	set @duration =  (select DURATION from FLIGHT where FLIGHT_NUMBER = @FID);
	if (@class = 'FIRST')
	BEGIN 
		set @PRICE = 120.0 * (@duration)
	END
	if (@class = 'BUSINESS')
	BEGIN 
		set @PRICE = 80.0 * (@duration)
	END
	if ( @class = 'ECONOMY')
	BEGIN 
		set @PRICE = 40.0 * (@duration)
	END
	INSERT INTO RESERVATION VALUES (@FID,@PID,@SEAT,@PRICE,@CLASS);
END

/*
DROP PROCEDURE RESERVE

declare @PRICE FLOAT ,@SEAT INTEGER
exec RESERVE 'SQ402','ECONOMY','100',@PRICE OUT,@SEAT OUT

print 'SEAT RESERVED  ' + convert(char(4),@SEAT) + 'with price ' + convert(char(5),@PRICE) 
*/