CREATE PROCEDURE SEARCH_FLIGHT @ARRC CHAR(30) null,@DEPC CHAR(30) null,@YEAR INTEGER,@MONTH INTEGER,@DAY INTEGER
AS
BEGIN
	SELECT * 
	FROM FLIGHT 
	WHERE ((@ARRC IS NOT NULL AND ARRIVAL_COUNTRY = @ARRC) OR (@ARRC IS NULL))-- AND ARRIVAL_COUNTRY LIKE '%')) 
	AND ( (@DEPC IS NOT NULL AND DEPARTURE_COUNTRY = @DEPC) OR (@DEPC IS NULL))-- AND DEPARTURE_COUNTRY LIKE '%')) 
	AND ((@YEAR >0 AND DATEPART(yy, DEPARTURE_TIME) = @YEAR) OR (@YEAR <= 0 )) --For year
	AND ((@MONTH >0 AND DATEPART(mm, DEPARTURE_TIME) = @MONTH) OR (@MONTH <= 0 ) ) --For month
	AND ((@DAY >0 AND DATEPART(dd, DEPARTURE_TIME) = @DAY) OR (@DAY <= 0 ) )--For day

END

drop procedure SEARCH_FLIGHT
EXEC SEARCH_FLIGHT null,'Emirates',0,2,0